apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-connection-configmap
  labels:
    app: mvc
data:
  db-connection-string: Server=mssql-deployment;Database=ProdcutsDB;User=SA;Password=MyC0m9l&xP@ssw0rd;
